name: Lighthouse CI Result Transformer
description: Handle easily the Lighthouse CI results

inputs:
  resultsPath:
    description: The LightHouse CI outputs.resultsPath
    required: true
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    default: ${{ github.token }}
    required: false
  githubComment:
    description: Should the action post the result as a comment
    default: 'false'
  slackWebhookUrl:
    description: The URL of the Slack Webhook

runs:
  using: node16
  main: dist/index.js
